apiVersion: v1
kind: Service
metadata:
  name: tondra
spec:
  type: NodePort
  selector:
          app: tondra
  ports:
   - name: http 
     nodePort: 32111     
     port: 8080 
     #targetPort: 80
          
