apiVersion: v1
kind: Pod
metadata: 
   name: alpine
   labels: 
       app: apine
spec:
   containers:
     - name: alpine
       image: alpine:3.18.4
       envFrom:
               - configMapRef:
                       name: mysql-config
       command: ["echo" , "$(TEST_CM)"]                
