apiVersion: v1
kind: Pod
metadata: 
   name: alpine
   labels: 
       app: apine
spec:
   containers:
     - name: alpine
       image: alpine:3.18.4
       command: ["sleep","infinity"]
       volumeMounts:
           - name: config
             mountPath: /config
   
           - name : nginx-config
             mountPath: /etc/nginx      
   volumes:
      - name: config
        configMap:
                name: mysql-config    
      - name: nginx-config
        configMap:
                name: nginx-config
