apiVersion: apps/v1
kind: StatefulSet 
metadata:
        name: mysql
spec:
   replicas: 1
   selector:
           matchLabels: 
                 app: mysql 
   template:
      metadata:
           labels:
                app: mysql
      spec:
          containers:
             - name: mysql
               image: mysql:8
               envFrom:
                  - secretRef:
                      name: mysql-config           
