apiVersion: v1
kind: Pod
metadata:
   name: test
   labels:
      app.kubernetes.io/name: alpine
      app.kubernetes.io/part-of: kubernetes-complete-reference
      app.kubernetes.io/created-by: m
spec:
   containers:
     - name: alpine
       image: alpine:latest
       command: ["sleep" , "infinity"]
          
       volumeMounts:
         - name: nfs-volume
           mountPath: /nfs
   volumes:
      - name: nfs-volume
        nfs:
           server: 192.168.56.19
           path: /data
           readOnly: false
  
              
