apiVersion: batch/v1
kind: CronJob
metadata: 
   name: test
spec: 
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
     spec:
        backoffLimit: 3 
        completions: 1
        template:
           spec:
              restartPolicy: Never
              containers:
                 - name: test
                   image: alpine:latest
                   command: ["sleep", "120"]   
