apiVersion: v1
kind: ReplicationController
metadata:
     name: nginx
spec:
    replicas: 2
    template:
            metadata:
              labels: 
                 app: nginx

            spec:
               containers:
                 - name: nginx
                   image: nginx:alpine
    selector:
       app: nginx
