apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  dnsConfig:
    nameservers:
     - 1.1.1.1
  containers:
    - name: test
      image: alpine:latest 
      command: ["cat", "/etc/resolv.conf"] 
