apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    containers:
      - name: test
        image: alpine:latest 
        command: ["nslookup", "test"] 
