apiVersion: v1
kind: Pod
metadata:
  name: test3
spec:
    containers:
      - name: test3
        image: alpine:latest 
        command: ["sleep", "1000"] 
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits: 
            cpu: 100m
            memory: 50Mi
