apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
    imagePullSecrets:
       - name: myreg
    containers:
      - name: nginx
        image: parib90228/nginx:alpine 
     
        
               
