apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
     initContainers:
        - name: test
          image: alpine:latest
          command: ["echo", "Hello world"] 
        - name: sleeper
          image: alpine:latest
          command: ["sleep", "10"] 
     containers:
      - name: nginx
        image: nginx:alpine 
     
        
               
