apiVersion: apps/v1
kind: ReplicaSet
metadata:
     name: nginx25
spec:
    replicas: 0   #1  2  3  3
    selector:
         matchLabels:
              app: nginx 

    template:
         metadata:
              labels: 
                app: nginx

         spec:
            containers:
                - name: nginx
                  image: nginx:1.25

---                  
apiVersion: apps/v1
kind: ReplicaSet
metadata:
     name: nginx24
spec:
    replicas: 3   #3  2  1  0
    selector:
         matchLabels:
              app: nginx 

    template:
         metadata:
              labels: 
                app: nginx

         spec:
            containers:
                - name: nginx
                  image: nginx:1.24

