apiVersion: apps/v1
kind: Deployment
metadata:
     name: nginx
spec:
    replicas: 5
    revisionHistoryLimit: 10
    strategy:
       rollingUpdate:
         maxSurge: 25%
         maxUnavailable: 25%
       type: RollingUpdate

    selector:
       matchLabels:
           app: nginx 

    template:
         metadata:
            labels: 
                app: nginx

         spec:
            containers:
               - name: nginx
                 image: nginx:1.25
