apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: LoadBalancer
  selector:
          app: nginx
  ports:
   - name: http 
     nodePort: 32111     
     port: 80 
     targetPort: 80
          
