apiVersion: v1
kind: Pod
metadata: 
   name: test
   labels: 
       app: test
spec:
   containers:
     - name: test
       image: nginx:alpine      
       livenessProbe:
               periodSeconds: 3
               successThreshold: 1
               failureThreshold: 2
               tcpSocket:
                       port: 80
                       
